package tsisyk.app.desertandcandies.view.avatars

import tsisyk.app.desertandcandies.R.drawable.*
import tsisyk.app.desertandcandies.model.Avatar

object AvatarStore {
    val AVATARS: List<Avatar> by lazy {
        val avatars = mutableListOf<Avatar>()

        avatars.add(Avatar(ic_desert_01))
        avatars.add(Avatar(ic_desert_02))
        avatars.add(Avatar(ic_desert_03))
        avatars.add(Avatar(ic_desert_04))
        avatars.add(Avatar(ic_desert_05))
        avatars.add(Avatar(ic_desert_06))
        avatars.add(Avatar(ic_desert_07))
        avatars.add(Avatar(ic_desert_08))
        avatars.add(Avatar(ic_desert_09))
        avatars.add(Avatar(ic_desert_10))
        avatars.add(Avatar(ic_desert_11))
        avatars.add(Avatar(ic_desert_12))
        avatars.add(Avatar(ic_desert_13))
        avatars.add(Avatar(ic_desert_14))
        avatars.add(Avatar(ic_desert_15))
        avatars.add(Avatar(ic_desert_16))
        avatars.add(Avatar(ic_desert_17))
        avatars.add(Avatar(ic_desert_18))
        avatars.add(Avatar(ic_desert_19))
        avatars.add(Avatar(ic_desert_20))
        avatars.add(Avatar(ic_desert_21))
        avatars.add(Avatar(ic_desert_22))
        avatars.add(Avatar(ic_desert_23))
        avatars.add(Avatar(ic_desert_24))
        avatars.add(Avatar(ic_desert_25))
        avatars.add(Avatar(ic_desert_26))
        avatars.add(Avatar(ic_desert_27))
        avatars.add(Avatar(ic_desert_28))
        avatars.add(Avatar(ic_desert_29))
        avatars.add(Avatar(ic_desert_30))
        avatars.add(Avatar(ic_desert_41))
        avatars.add(Avatar(ic_desert_42))
        avatars.add(Avatar(ic_desert_43))
        avatars.add(Avatar(ic_desert_44))
        avatars.add(Avatar(ic_desert_45))
        avatars.add(Avatar(ic_desert_46))
        avatars.add(Avatar(ic_desert_47))
        avatars.add(Avatar(ic_desert_48))
        avatars.add(Avatar(ic_desert_49))
        avatars.add(Avatar(ic_desert_50))
        avatars.add(Avatar(ic_desert_51))
        avatars.add(Avatar(ic_desert_52))
        avatars.add(Avatar(ic_desert_53))
        avatars.add(Avatar(ic_desert_54))
        avatars.add(Avatar(ic_desert_55))
        avatars.add(Avatar(ic_desert_56))
        avatars.add(Avatar(ic_desert_57))
        avatars.add(Avatar(ic_desert_58))
        avatars.add(Avatar(ic_desert_59))
        avatars.add(Avatar(ic_desert_70))
        avatars.add(Avatar(ic_desert_71))
        avatars.add(Avatar(ic_desert_72))
        avatars.add(Avatar(ic_desert_73))
        avatars.add(Avatar(ic_desert_74))
        avatars.add(Avatar(ic_desert_75))
        avatars.add(Avatar(ic_desert_76))
        avatars.add(Avatar(ic_desert_77))
        avatars.add(Avatar(ic_desert_78))
        avatars.add(Avatar(ic_desert_79))
        avatars.add(Avatar(ic_desert_80))
        avatars.add(Avatar(ic_desert_81))
        avatars.add(Avatar(ic_desert_82))
        avatars.add(Avatar(ic_desert_83))
        avatars.add(Avatar(ic_desert_84))
        avatars.add(Avatar(ic_desert_85))
        avatars.add(Avatar(ic_desert_86))
        avatars.add(Avatar(ic_desert_87))
        avatars.add(Avatar(ic_desert_88))
        avatars.add(Avatar(ic_desert_89))
        avatars.add(Avatar(ic_desert_90))
        avatars.add(Avatar(ic_desert_91))
        avatars.add(Avatar(ic_desert_92))
        avatars.add(Avatar(ic_desert_93))
        avatars.add(Avatar(ic_desert_94))
        avatars.add(Avatar(ic_desert_95))
        avatars.add(Avatar(ic_desert_96))
        avatars.add(Avatar(ic_desert_97))
        avatars.add(Avatar(ic_desert_98))
        avatars.add(Avatar(ic_desert_99))

        avatars
    }
}